
# Introduction 

We conduct a statistical analysis for multi-use recreational trails in the Bridger Mountains to estimate the volume and location of recreation. Headwaters economics along with [OTHER COUNTER OWNERS] have deplyed trail camera counters along a [random?] selection of recreational trails in the Bridger Mountains focused on the summer months of 2021. 

The goals of this analysis is to (1) develop a predictive model of recreational trail use using data from trail counters, weather, trail characteristics, and novel data sources provided by Headwaters Economics and (2) Apply the statistical model to demonstrate trade offs in predictive accuracy for different applications. The aim is to inform policy/methods adopted by land management agencies (e.g. U.S. Forest Service); also good for local decision makers. Auxiliary data provided through partnerships with Strava and AllTrails was explored to examine the predictive [power?] of these data sources. We conducted analysis of these pilot data for [NUMBER] of trails  subsections with trail cameras deployed.  We used a Generalized Additive Model approach which allows for [GAM DETAILS]. We applied a framework of HGAMS [explain, cite paper] and various temporal autoregressive structures on the errors to address the spatial nesting and temporal correlation of these data, respectively. Using [details] we present results for several models explored and examine the prediction estimates and residuals for both in- and out-of-sample trail subsections. We also provide recommendations on sampling effort (i.e. the spatial and temporal spread of trail camera deployment need to provide reliable predictions of trail use over time) for use both in the Bridgers and more generally. 