# Spatial Network Generalized Additive Mixture Model

```{r, eval =  T}
library(here)
library(raster) # DEM for map
library(tidyverse) # data processing and plotting functions
library(sf) # tidy spatial data and mapping
library(mgcv) # fit GAMs and GAMMs
library(archdata) # source for the Oxford Pots data
library(tidygraph) # tidy network processing
# devtools::install_github('thomasp85/ggraph') # need dev version of ggraph 
library(ggraph) # network plots
# devtools::install_github('nspope/corMLPE')
library(corMLPE) # network correlation structure for undirected networks
# library(ggmap) # for geocoding, but not used by default (see below)
library(ggspatial) # scale bar for maps
library(maps) # country outlines for maps


#helps to format this document 
#by default the included code chunks do not appear in the report view
knitr::opts_chunk$set(echo = F, 
                      eval = F,
                      include = F,
                      message = F, 
                      # cache=TRUE, 
                      warning=FALSE, 
                      error=FALSE, 
                      root.dir = normalizePath(".."))

source(here("scripts/01.01-OrganizeSpatialData.R"))
source(here("scripts/01.02-LoadFunctions.R"))


runall = F
```



```{r, eval = F}
net %E>%
  arrange(max.camera) %N>%
ggraph(., layout = 'manual',
       x = as_tibble(.)$x, y = as_tibble(.)$y
       ) +
  # geom_sf(data = uk_boundary, fill = NA) +
  geom_edge_link(aes(colour = max.camera), edge_width = 2, lineend = 'round') +
  geom_sf(data = st_as_sf(net %>% st_zm, "nodes"), 
         color = "grey50"
          ) +
  geom_sf(data = cameras_sf,
          aes(
            color = factor(subsectionname)), shape = 2) +
  scale_edge_color_viridis(guide = 'legend', name = 'Pottery \nfrom origin site',
                           labels = paste0(seq(5, 20, 5), '%'),
                           breaks = seq(5, 20, 5)) +
  annotation_scale(location = 'br', style = 'ticks') +
  # coord_sf(datum = NA, xlim = c(-6, 2), ylim = c(50, 53.8)) +
  ggtitle('Ceramic distribution in Roman Britain', 
          'Percent late Romano-British pottery produced in Oxford and New Forest \n \n \n') +
  theme_void()
```

```{r, eval = T}
trail_dat <-  net %E>% as_tibble
trail_dat$wday <- as.integer(trail_dat$wday)

if(runall){
  
trail_model <-  gamm(max.camera ~  
                       s(yday, bs="cc") +
                         s(month, k = 7) +
                         s(wday,
                           bs = "cc", k = 7) +
                         s(daily_aqi_value) +
                         s(temp_max_f) +
                         s(precipitation_in) +
                        s(totallength_miles) +
                        total_traveltime +
                         max.count,
                      knots = list(yday = c(0,365)),
           # family =  quasipoisson(), # overdispersed count data
           family =  poisson(), # count data
           correlation = corMLPE(form = ~from + to), # symmetric network correlation structure
           # correlation = corAR1(),
           method = 'REML',
           # select = TRUE,
           data = trail_dat, 
           niterPQL = 30
           )

save(trail_model, 
     file=here("output/models/allT_spatial_gamm-corMLPE.rda"), 
     compress='xz')
}

load(file=here("output/models/allT_spatial_gamm-corMLPE.rda"))

```

```{r summary-spatial, eval = T}
summary(trail_model$gam)
```

```{r mod diagnoses, eval = T}
allTrail_mod <- trail_dat %>% 
  tidyr::drop_na(c('daily_aqi_value', "totallength_miles"))


with(allTrail_mod, tsDiagGamm(trail_model, timevar = yday,
                          observed = max.camera))

```

```{r mod draw, eval = T, echo=T}
gratia::draw(trail_model$gam)
```

```{r mod rootogram, eval = T, echo = T}

rg <- gratia::rootogram(trail_model$gam)
gratia::draw(rg)

sum(residuals(trail_model$gam, type = "pearson")^2) / df.residual(trail_model$gam)

```

```{r mod predictions, eval = T, echo = T, fig.cap="Assuming a well-fitted model, we would expect all trail subsections exhibiting similar patterns of dispersion around the 1-1 line (and as we are assuming the data is Poisson, the variance around the mean should equal the mean). Instead we see that variance around the predicted value is much higher for some trails such as Sacagawea Pass."}

#add the predicted values from the model 
allTrail_spatial_pred <- transform(allTrail_mod, 
                      mod = predict(trail_model$gam, 
                                      type = "response"))

ggplot(allTrail_spatial_pred, aes(x=mod, y=max.camera)) +
  facet_wrap(~subsectionF) +
  geom_point(alpha=0.1) +
  geom_abline() +
  labs(x="Predicted count", y="Observed count")
```

```{r modelG-predict-spatial, eval = T, echo=FALSE}
gamm_mod_pred <- predict(trail_model$gam, se.fit=TRUE, type = "response")
allTrail_spatial_pred <- transform(allTrail_mod, 
                 mod = gamm_mod_pred$fit, 
                 mod_se = gamm_mod_pred$se.fit)
all_pred <- ggplot(data=allTrail_spatial_pred, aes(x=yday, y=max.camera, group=subsectionF)) +
  facet_wrap(~subsectionF) +
  geom_ribbon(aes(ymin=(mod-2*mod_se),
                  ymax=(mod+2*mod_se)), alpha=0.25) +
  geom_line(aes(y=(mod), col = trailname)) +
  geom_point(aes(color = trailname)) +
  labs(x=expression("Day of Year"),
       y=expression("Trail use"))

## turn this into two graphs with high/low trail use so scales are different and we can see low trail use subsections better

high_pred <- ggplot(data=filter(allTrail_spatial_pred, subsectionF %in% high_use),
                   aes(x=yday, y=max.camera, 
                       group=subsectionF)) +
  facet_wrap(~subsectionF, ncol = 3) +
  geom_ribbon(aes(ymin=(mod-2*mod_se),
                  ymax=(mod+2*mod_se)), alpha=0.25) +
  geom_line(aes(y=(mod), col = trailname)) +
  geom_point(aes(color = trailname), size = 1) +
  labs(x=expression("Day of Year"),
       y=expression("Trail use")) + 
  theme(legend.position="bottom")

# ggsave(filename = here::here("output/figures/high_pred_modG.pdf"),
#        plot = high_pred_G,
#        height = 8.5, 
#        width = 13,
#        dpi=700)

low_pred <- ggplot(data=filter(allTrail_spatial_pred, subsectionF %notin% c("NA", high_use)),
                   aes(x=yday, y=max.camera, 
                       group=subsectionF)) +
  facet_wrap(~subsectionF, ncol = 3) +
  geom_ribbon(aes(ymin=(mod-2*mod_se),
                  ymax=(mod+2*mod_se)), alpha=0.25) +
  geom_line(aes(y=(mod), col = trailname)) +
  geom_point(aes(color = trailname), size = 1) +
  labs(x=expression("Day of Year"),
       y=expression("Trail use")) + 
  theme(legend.position="bottom")

# ggsave(filename = here::here("output/figures/low_pred_modG.pdf"),
#        plot = low_pred_G,
#        height = 8.5, 
#        width = 13,
#        dpi=700)
```